// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjtVFhNoONM6XaugGJjSAhV3tc5rgaYVo',
    appId: '1:1096689355619:web:20410831b50ca1f2b0a156',
    messagingSenderId: '1096689355619',
    projectId: 'den-tech-smile',
    authDomain: 'den-tech-smile.firebaseapp.com',
    storageBucket: 'den-tech-smile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXkYkwxoLtj17ajkjMArTw6VrEr8B-kgs',
    appId: '1:1096689355619:android:f9b295a7151c97e7b0a156',
    messagingSenderId: '1096689355619',
    projectId: 'den-tech-smile',
    storageBucket: 'den-tech-smile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0JfH199uYr8TFAPAKGxNpDdWmnHelor0',
    appId: '1:1096689355619:ios:282d17637f7364f8b0a156',
    messagingSenderId: '1096689355619',
    projectId: 'den-tech-smile',
    storageBucket: 'den-tech-smile.firebasestorage.app',
    iosBundleId: 'com.example.dentechSmile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0JfH199uYr8TFAPAKGxNpDdWmnHelor0',
    appId: '1:1096689355619:ios:282d17637f7364f8b0a156',
    messagingSenderId: '1096689355619',
    projectId: 'den-tech-smile',
    storageBucket: 'den-tech-smile.firebasestorage.app',
    iosBundleId: 'com.example.dentechSmile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjtVFhNoONM6XaugGJjSAhV3tc5rgaYVo',
    appId: '1:1096689355619:web:f9a84482495f7a64b0a156',
    messagingSenderId: '1096689355619',
    projectId: 'den-tech-smile',
    authDomain: 'den-tech-smile.firebaseapp.com',
    storageBucket: 'den-tech-smile.firebasestorage.app',
  );
}
